name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
#        with:
#          context: .
#          file: phpdocker/php-fpm/Dockerfile
      - name: Build and push the image
        run: |
          docker login --username petermarynczak --password ${{ secrets.GH_PAT }} ghcr.io
          docker build /phpdocker/php-fpm --tag ghcr.io/petermarynczak/ghcr-nginx:latest
          docker push ghcr.io/petermarynczak/ghcr-nginx:latest
#      - name: Checkout repository
#        uses: actions/checkout@v2
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#
#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GH_PAT }}
#
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          file: phpdocker/php-fpm/Dockerfile
#          push: true
#          tags: ghcr.io/petermaynczak/ghcr-nginx:latest
